<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SimpleDayCounter</AssemblyName>
    <RootNamespace>SimpleDayCounter</RootNamespace>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>

    <Product>SimpleDayCounter</Product>
    <Authors>debojitsantra</Authors>
    <Company>debojitsantra</Company>
    <Description>Lightweight draggable day-countdown widgets for your Windows desktop.</Description>
    <Copyright>Copyright © debojitsantra</Copyright>

    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <!-- app.ico is optional-->
    <Resource Include="Resources\app.ico" Condition="Exists('Resources\app.ico')" />
  </ItemGroup>

</Project>
